In [1]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

In [2]:
X,y = spiral_data(samples = 100, classes = 3)

In [3]:
class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs,n_neurons)
        self.biases = np.zeros((1,n_neurons))

    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights) + self.biases
        

In [4]:
class Activation_ReLU:
    def forward(self,inputs):
        self.output = np.maximum(0,inputs)
        
class Activation_Softmax:
    def forward(self,inputs):
        exp_values = np.exp(inputs - np.max(inputs,axis=1,keepdims=True))
        probabilities = exp_values / np.sum(exp_values,axis=1,keepdims=True)
        self.output = probabilities
        

In [5]:
dense1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()

dense2 = Layer_Dense(3,3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

[[0.33333333 0.33333333 0.33333333]
 [0.33333329 0.33333354 0.33333317]
 [0.33333328 0.3333337  0.33333301]
 [0.33333351 0.33333348 0.333333  ]
 [0.3333332  0.33333411 0.33333269]]
